import { User, Task, PettyCashFund, Expense, Settlement, FollowUp, AuditLog, NotificationItem } from '../types/domain';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-1',
    name: 'سلطان المنصوري',
    email: 'sultan@ops.ae',
    role: 'admin',
    roleTitleAr: 'المدير التنفيذي للعمليات',
    phone: '+971 50 123 4567',
    department: 'الإدارة العليا',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    active: true,
    assignedFundsCount: 1,
    activeTasksCount: 4,
  },
  {
    id: 'usr-2',
    name: 'م. راشد المزروعي',
    email: 'rashed@ops.ae',
    role: 'ops_manager',
    roleTitleAr: 'مدير العمليات والمشاريع',
    phone: '+971 50 987 6543',
    department: 'العمليات والمشاريع',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    active: true,
    assignedFundsCount: 1,
    activeTasksCount: 6,
  },
  {
    id: 'usr-3',
    name: 'فاطمة الكعبي',
    email: 'fatima@ops.ae',
    role: 'finance_officer',
    roleTitleAr: 'رئيس قسم التدقيق المالي',
    phone: '+971 52 345 6789',
    department: 'الإدارة المالية والرقابة',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    active: true,
    assignedFundsCount: 6,
    activeTasksCount: 3,
  },
  {
    id: 'usr-4',
    name: 'أحمد الحمادي',
    email: 'ahmed@ops.ae',
    role: 'field_officer',
    roleTitleAr: 'مشرف فني ميداني',
    phone: '+971 55 456 7890',
    department: 'الفريق الميداني (المنطقة الغربية)',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    active: true,
    assignedFundsCount: 1,
    activeTasksCount: 5,
  },
  {
    id: 'usr-5',
    name: 'خالد الظاهري',
    email: 'khaled@ops.ae',
    role: 'field_officer',
    roleTitleAr: 'مهندس صيانة موقع',
    phone: '+971 56 678 1234',
    department: 'الفريق الميداني (دبي والشمالية)',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    active: true,
    assignedFundsCount: 2,
    activeTasksCount: 4,
  },
  {
    id: 'usr-6',
    name: 'طارق السويدي',
    email: 'tariq@ops.ae',
    role: 'field_officer',
    roleTitleAr: 'مشرف تشغيل ومواقع',
    phone: '+971 50 445 9911',
    department: 'فريق الطاقة والمحطات (أبوظبي والعين)',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    active: true,
    assignedFundsCount: 1,
    activeTasksCount: 3,
  },
  {
    id: 'usr-7',
    name: 'سارة الهاشمي',
    email: 'sara@ops.ae',
    role: 'finance_officer',
    roleTitleAr: 'محاسب مشتريات وتدقيق عهد',
    phone: '+971 55 778 2233',
    department: 'الإدارة المالية',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    active: true,
    assignedFundsCount: 3,
    activeTasksCount: 2,
  },
  {
    id: 'usr-8',
    name: 'مريم الشامسي',
    email: 'maryam@ops.ae',
    role: 'viewer',
    roleTitleAr: 'محلل جودة وامتثال',
    phone: '+971 54 888 9900',
    department: 'الجودة والرقابة والمطابقة',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    active: true,
    assignedFundsCount: 0,
    activeTasksCount: 0,
  }
];

export const INITIAL_FUNDS: PettyCashFund[] = [
  {
    id: 'fund-1',
    name: 'عهدة مشاريع المنطقة الصناعية A',
    code: 'PCF-2026-001',
    holderId: 'usr-4',
    holderName: 'أحمد الحمادي',
    holderDepartment: 'الفريق الميداني (المنطقة الغربية)',
    totalAllocation: 25000,
    currentBalance: 8450,
    spentBalance: 16550,
    currency: 'AED',
    status: 'warning',
    warningThreshold: 35,
    lastReplenishedDate: '2026-08-15',
    purpose: 'تغطية نفقات المشتريات المباشرة ومواد الصيانة السريعة في الموقع الصناعي.',
    notes: 'تم استهلاك 66% من العهدة، تتطلب تسوية قريبة لإعادة التغذية قبل نهاية الشهر.',
  },
  {
    id: 'fund-2',
    name: 'عهدة الصيانة والتشغيل الميداني',
    code: 'PCF-2026-002',
    holderId: 'usr-5',
    holderName: 'خالد الظاهري',
    holderDepartment: 'الفريق الميداني (دبي والشمالية)',
    totalAllocation: 15000,
    currentBalance: 10850,
    spentBalance: 4150,
    currency: 'AED',
    status: 'active',
    warningThreshold: 25,
    lastReplenishedDate: '2026-09-01',
    purpose: 'قطع غيار طارئة، رسوم تصاريح فنية ومحروقات مولدات الطوارئ.',
    notes: 'حالة السيولة مستقرة ومعدل الصرف ضمن الحدود المخطط لها.',
  },
  {
    id: 'fund-3',
    name: 'عهدة نثريات وضيافة العمليات',
    code: 'PCF-2026-003',
    holderId: 'usr-2',
    holderName: 'م. راشد المزروعي',
    holderDepartment: 'العمليات والمشاريع',
    totalAllocation: 10000,
    currentBalance: 6850,
    spentBalance: 3150,
    currency: 'AED',
    status: 'active',
    warningThreshold: 20,
    lastReplenishedDate: '2026-09-05',
    purpose: 'استقبال الوفود، اجتماعات المهندسين الميدانيين والمستلزمات المكتبية للموقع.',
    notes: 'تغطي مصاريف اجتماعات التنسيق مع الدوائر الحكومية والبلديات.',
  },
  {
    id: 'fund-4',
    name: 'عهدة الطوارئ والسلامة المهنية',
    code: 'PCF-2026-004',
    holderId: 'usr-1',
    holderName: 'سلطان المنصوري',
    holderDepartment: 'الإدارة العليا',
    totalAllocation: 30000,
    currentBalance: 27500,
    spentBalance: 2500,
    currency: 'AED',
    status: 'active',
    warningThreshold: 20,
    lastReplenishedDate: '2026-09-10',
    purpose: 'معدات الوقاية الشخصية الطارئة، معالجة الحوادث وسيارات الإسناد السريع.',
    notes: 'صندوق احتياطي عالي السقف مخصص للحالات الحرجة وتجهيزات الدفاع المدني.',
  },
  {
    id: 'fund-5',
    name: 'عهدة مشاريع محطة الطاقة الشمسية - العين',
    code: 'PCF-2026-005',
    holderId: 'usr-6',
    holderName: 'طارق السويدي',
    holderDepartment: 'فريق الطاقة والمحطات (أبوظبي والعين)',
    totalAllocation: 20000,
    currentBalance: 4200,
    spentBalance: 15800,
    currency: 'AED',
    status: 'warning',
    warningThreshold: 30,
    lastReplenishedDate: '2026-08-25',
    purpose: 'تنظيف وتبريد الألواح الكهروضوئية ومستلزمات صيانة العواكس الكهربائية.',
    notes: 'الرصيد المتبقي 21% فقط (أقل من نسبة التنبيه 30%). جاري إعداد التسوية الدورية.',
  },
  {
    id: 'fund-6',
    name: 'عهدة الخدمات اللوجستية والحركة',
    code: 'PCF-2026-006',
    holderId: 'usr-5',
    holderName: 'خالد الظاهري',
    holderDepartment: 'الفريق الميداني (دبي والشمالية)',
    totalAllocation: 12000,
    currentBalance: 9600,
    spentBalance: 2400,
    currency: 'AED',
    status: 'active',
    warningThreshold: 25,
    lastReplenishedDate: '2026-09-08',
    purpose: 'بوابات التعرفة المرورية (سالك)، وقود شاحنات النقل الداخلي ورسوم فحص المركبات.',
    notes: 'مخصصة لحركة الأسطول التشغيلي بين المواقع والمستودعات.',
  }
];

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: 'exp-1',
    code: 'EXP-901',
    fundId: 'fund-1',
    fundName: 'عهدة مشاريع المنطقة الصناعية A',
    amount: 3200,
    taxAmount: 160,
    totalWithTax: 3360,
    category: 'materials',
    description: 'شراء كابلات كهربائية نحاسية 16 ملم ومفاتيح قواطع أوتوماتيكية للموقع',
    invoiceNumber: 'INV-AL-BARQ-4481',
    vendorName: 'شركة البرق لمعدات الطاقة',
    hasReceipt: true,
    receiptUrl: 'https://images.unsplash.com/photo-1607344645866-009c320c5ab8?w=500&auto=format&fit=crop&q=80',
    status: 'approved',
    submittedBy: 'أحمد الحمادي',
    submittedAt: '2026-09-12 10:30',
    approvedBy: 'فاطمة الكعبي',
    approvedAt: '2026-09-12 14:15',
    taskId: 'tsk-1',
    taskTitle: 'تحديث المحطة الكهربائية الفرعية في القطاع C',
  },
  {
    id: 'exp-2',
    code: 'EXP-902',
    fundId: 'fund-1',
    fundName: 'عهدة مشاريع المنطقة الصناعية A',
    amount: 1450,
    taxAmount: 72.5,
    totalWithTax: 1522.5,
    category: 'fuel',
    description: 'تزويد ديزل للشاحنات الثقيلة والمولدات الميدانية أثناء صيانة الخطوط',
    invoiceNumber: 'ADNOC-D-77218',
    vendorName: 'أدنوك للتوزيع',
    hasReceipt: true,
    receiptUrl: 'https://images.unsplash.com/photo-1545459720-aac8509eb02c?w=500&auto=format&fit=crop&q=80',
    status: 'approved',
    submittedBy: 'أحمد الحمادي',
    submittedAt: '2026-09-14 08:45',
    approvedBy: 'فاطمة الكعبي',
    approvedAt: '2026-09-14 11:20',
    taskId: 'tsk-2',
    taskTitle: 'فحص وتشغيل مضخات التبريد المركزية',
  },
  {
    id: 'exp-3',
    code: 'EXP-903',
    fundId: 'fund-2',
    fundName: 'عهدة الصيانة والتشغيل الميداني',
    amount: 850,
    taxAmount: 42.5,
    totalWithTax: 892.5,
    category: 'tools',
    description: 'استبدال حساسات الضغط ومقاييس الحرارة الرقمية التالفة',
    invoiceNumber: 'TECH-SENS-1029',
    vendorName: 'مؤسسة التقنية للحساسات الدقيقة',
    hasReceipt: true,
    status: 'pending_approval',
    submittedBy: 'خالد الظاهري',
    submittedAt: '2026-09-18 16:10',
    taskId: 'tsk-3',
    taskTitle: 'معايرة أنظمة قياس الضغط الهوائي',
  },
  {
    id: 'exp-4',
    code: 'EXP-904',
    fundId: 'fund-1',
    fundName: 'عهدة مشاريع المنطقة الصناعية A',
    amount: 2800,
    taxAmount: 140,
    totalWithTax: 2940,
    category: 'maintenance',
    description: 'صيانة طارئة لرافعة الموقع الهيدروليكية واستبدال الزيوت التالفة',
    invoiceNumber: 'HYD-SERV-883',
    vendorName: 'ورشة الهيدروليك التخصصية',
    hasReceipt: true,
    status: 'pending_approval',
    submittedBy: 'أحمد الحمادي',
    submittedAt: '2026-09-19 09:20',
    taskId: 'tsk-1',
    taskTitle: 'تحديث المحطة الكهربائية الفرعية في القطاع C',
  },
  {
    id: 'exp-5',
    code: 'EXP-905',
    fundId: 'fund-3',
    fundName: 'عهدة نثريات وضيافة العمليات',
    amount: 620,
    taxAmount: 31,
    totalWithTax: 651,
    category: 'hospitality',
    description: 'ضيافة وفد التفتيش والبلدية ومستلزمات المياه للمهندسين في الموقع',
    invoiceNumber: 'CAFE-HOSP-512',
    vendorName: 'الضيافة العربية لخدمات التموين',
    hasReceipt: true,
    status: 'approved',
    submittedBy: 'م. راشد المزروعي',
    submittedAt: '2026-09-16 13:00',
    approvedBy: 'فاطمة الكعبي',
    approvedAt: '2026-09-16 15:30',
  },
  {
    id: 'exp-6',
    code: 'EXP-906',
    fundId: 'fund-1',
    fundName: 'عهدة مشاريع المنطقة الصناعية A',
    amount: 7500,
    taxAmount: 375,
    totalWithTax: 7875,
    category: 'tools',
    description: 'شراء مولد طوارئ متنقل 10KVA للموقع الجديد (تجاوز السقف المحدد)',
    invoiceNumber: 'GEN-PWR-331',
    vendorName: 'شركة القوة للمولدات والمعدات',
    hasReceipt: true,
    status: 'rejected',
    submittedBy: 'أحمد الحمادي',
    submittedAt: '2026-09-17 11:15',
    approvedBy: 'فاطمة الكعبي',
    approvedAt: '2026-09-17 14:00',
    rejectionReason: 'تجاوز حد الصرف الفردي للعهدة النقدية (5,000 درهم). يتطلب أمر شراء رسمي من إدارة العقود والمشتريات.',
  },
  {
    id: 'exp-7',
    code: 'EXP-907',
    fundId: 'fund-2',
    fundName: 'عهدة الصيانة والتشغيل الميداني',
    amount: 450,
    taxAmount: 22.5,
    totalWithTax: 472.5,
    category: 'transport',
    description: 'رسوم نقل قطع الغيار المستعجلة عبر الشحن السريع للموقع',
    invoiceNumber: 'EXP-LOG-671',
    vendorName: 'أرامكس اللوجستية',
    hasReceipt: true,
    status: 'settled',
    submittedBy: 'خالد الظاهري',
    submittedAt: '2026-09-10 14:00',
    approvedBy: 'فاطمة الكعبي',
    approvedAt: '2026-09-10 16:30',
  },
  {
    id: 'exp-8',
    code: 'EXP-908',
    fundId: 'fund-5',
    fundName: 'عهدة مشاريع محطة الطاقة الشمسية - العين',
    amount: 3800,
    taxAmount: 190,
    totalWithTax: 3990,
    category: 'materials',
    description: 'فلاتر خاصة وسائل تنظيف متوازن كيميائياً لألواح الطاقة الشمسية',
    invoiceNumber: 'SOLAR-CLN-882',
    vendorName: 'مؤسسة شمس المستقبل لحلول الطاقة',
    hasReceipt: true,
    status: 'approved',
    submittedBy: 'طارق السويدي',
    submittedAt: '2026-09-08 09:15',
    approvedBy: 'سارة الهاشمي',
    approvedAt: '2026-09-08 12:40',
    taskId: 'tsk-6',
    taskTitle: 'غسيل وتطهير مصفوفات الألواح الشمسية - القطاع الجنوبي',
  },
  {
    id: 'exp-9',
    code: 'EXP-909',
    fundId: 'fund-5',
    fundName: 'عهدة مشاريع محطة الطاقة الشمسية - العين',
    amount: 2100,
    taxAmount: 105,
    totalWithTax: 2205,
    category: 'fuel',
    description: 'وقود ديزل لتشغيل صهاريج مياه الغسيل في محطة العين',
    invoiceNumber: 'ADNOC-ALN-4421',
    vendorName: 'أدنوك للتوزيع',
    hasReceipt: true,
    status: 'approved',
    submittedBy: 'طارق السويدي',
    submittedAt: '2026-09-11 11:00',
    approvedBy: 'سارة الهاشمي',
    approvedAt: '2026-09-11 14:10',
    taskId: 'tsk-6',
    taskTitle: 'غسيل وتطهير مصفوفات الألواح الشمسية - القطاع الجنوبي',
  },
  {
    id: 'exp-10',
    code: 'EXP-910',
    fundId: 'fund-6',
    fundName: 'عهدة الخدمات اللوجستية والحركة',
    amount: 1200,
    taxAmount: 60,
    totalWithTax: 1260,
    category: 'maintenance',
    description: 'تغيير إطارات أمامية لشاحنة الإسناد الميداني رقم 4',
    invoiceNumber: 'TYRE-PRO-992',
    vendorName: 'مركز الفطيم للإطارات والخدمة السريعة',
    hasReceipt: true,
    status: 'approved',
    submittedBy: 'خالد الظاهري',
    submittedAt: '2026-09-13 15:20',
    approvedBy: 'فاطمة الكعبي',
    approvedAt: '2026-09-13 17:00',
    taskId: 'tsk-7',
    taskTitle: 'الفحص الفني الدوري وتجديد ترخيص أسطول العمليات',
  },
  {
    id: 'exp-11',
    code: 'EXP-911',
    fundId: 'fund-4',
    fundName: 'عهدة الطوارئ والسلامة المهنية',
    amount: 2400,
    taxAmount: 120,
    totalWithTax: 2520,
    category: 'tools',
    description: 'شراء أحزمة أمان متطورة للعمل على المرتفعات وخوذ حماية متوافقة مع أوشا',
    invoiceNumber: 'SAFE-MAX-118',
    vendorName: 'مؤسسة الأمان القصوى لمعدات السلامة',
    hasReceipt: true,
    status: 'approved',
    submittedBy: 'سلطان المنصوري',
    submittedAt: '2026-09-11 10:00',
    approvedBy: 'فاطمة الكعبي',
    approvedAt: '2026-09-11 11:30',
    taskId: 'tsk-4',
    taskTitle: 'تجهيز موقع الإنشاءات للزيارة الرقابية السنوية',
  },
  {
    id: 'exp-12',
    code: 'EXP-912',
    fundId: 'fund-3',
    fundName: 'عهدة نثريات وضيافة العمليات',
    amount: 450,
    taxAmount: 22.5,
    totalWithTax: 472.5,
    category: 'hospitality',
    description: 'وجبات عمل واحتياجات قهوة ومياه لورشة التدريب على السلامة في الموقع',
    invoiceNumber: 'CATER-EX-703',
    vendorName: 'مطاعم الضيافة الميدانية',
    hasReceipt: true,
    status: 'approved',
    submittedBy: 'م. راشد المزروعي',
    submittedAt: '2026-09-17 12:30',
    approvedBy: 'فاطمة الكعبي',
    approvedAt: '2026-09-17 14:45',
    taskId: 'tsk-8',
    taskTitle: 'تنظيم ورشة تدريب السلامة لفرق الموقع الجديد',
  },
  {
    id: 'exp-13',
    code: 'EXP-913',
    fundId: 'fund-1',
    fundName: 'عهدة مشاريع المنطقة الصناعية A',
    amount: 1950,
    taxAmount: 97.5,
    totalWithTax: 2047.5,
    category: 'fuel',
    description: 'بنزين لمركبات المهندسين الميدانيين لتنفيذ الزيارات الرقابية الإلزامية',
    invoiceNumber: 'ENOC-FS-8812',
    vendorName: 'إينوك للتوزيع',
    hasReceipt: true,
    status: 'approved',
    submittedBy: 'أحمد الحمادي',
    submittedAt: '2026-09-15 16:45',
    approvedBy: 'فاطمة الكعبي',
    approvedAt: '2026-09-15 18:00',
  },
  {
    id: 'exp-14',
    code: 'EXP-914',
    fundId: 'fund-2',
    fundName: 'عهدة الصيانة والتشغيل الميداني',
    amount: 1350,
    taxAmount: 67.5,
    totalWithTax: 1417.5,
    category: 'materials',
    description: 'شراء دهانات حرارية ومواد عزل مانعة للصدأ لأنابيب غرف التبريد',
    invoiceNumber: 'PAINTS-IND-501',
    vendorName: 'جوتن للدهانات الصناعية',
    hasReceipt: true,
    status: 'approved',
    submittedBy: 'خالد الظاهري',
    submittedAt: '2026-09-16 09:30',
    approvedBy: 'سارة الهاشمي',
    approvedAt: '2026-09-16 11:15',
    taskId: 'tsk-2',
    taskTitle: 'فحص وتشغيل مضخات التبريد المركزية',
  },
  {
    id: 'exp-15',
    code: 'EXP-915',
    fundId: 'fund-5',
    fundName: 'عهدة مشاريع محطة الطاقة الشمسية - العين',
    amount: 4600,
    taxAmount: 230,
    totalWithTax: 4830,
    category: 'maintenance',
    description: 'استبدال محول جهد تالف في المحطة الفرعية B2 وضبط لوحة التزامن',
    invoiceNumber: 'ABB-REP-410',
    vendorName: 'المقاولون الهندسية لصيانة المحولات',
    hasReceipt: true,
    status: 'pending_approval',
    submittedBy: 'طارق السويدي',
    submittedAt: '2026-09-19 14:00',
    taskId: 'tsk-9',
    taskTitle: 'استبدال محول العزل ومراجعة منظومة التأريض لمحطة الطاقة',
  },
  {
    id: 'exp-16',
    code: 'EXP-916',
    fundId: 'fund-6',
    fundName: 'عهدة الخدمات اللوجستية والحركة',
    amount: 550,
    taxAmount: 27.5,
    totalWithTax: 577.5,
    category: 'transport',
    description: 'شحن مستندات ومخططات هندسية معتمدة عبر البريد السريع لإدارة التراخيص',
    invoiceNumber: 'DHL-EXP-9921',
    vendorName: 'دي إتش إل إكسبريس',
    hasReceipt: true,
    status: 'approved',
    submittedBy: 'خالد الظاهري',
    submittedAt: '2026-09-14 11:00',
    approvedBy: 'سارة الهاشمي',
    approvedAt: '2026-09-14 13:00',
  },
  {
    id: 'exp-17',
    code: 'EXP-917',
    fundId: 'fund-1',
    fundName: 'عهدة مشاريع المنطقة الصناعية A',
    amount: 1100,
    taxAmount: 55,
    totalWithTax: 1155,
    category: 'tools',
    description: 'مجموعة أدوات قطع وتوصيل الكابلات الكهربائية عازلة حتى 1000 فولت',
    invoiceNumber: 'KLEIN-TOOL-229',
    vendorName: 'مؤسسة المعدات الاحترافية',
    hasReceipt: true,
    status: 'approved',
    submittedBy: 'أحمد الحمادي',
    submittedAt: '2026-09-13 14:20',
    approvedBy: 'فاطمة الكعبي',
    approvedAt: '2026-09-13 16:00',
    taskId: 'tsk-1',
    taskTitle: 'تحديث المحطة الكهربائية الفرعية في القطاع C',
  },
  {
    id: 'exp-18',
    code: 'EXP-918',
    fundId: 'fund-2',
    fundName: 'عهدة الصيانة والتشغيل الميداني',
    amount: 3200,
    taxAmount: 160,
    totalWithTax: 3360,
    category: 'maintenance',
    description: 'إصلاح ضاغط الهواء الترددي الرئيسي في ورشة الصيانة واستبدال الصمامات',
    invoiceNumber: 'AIR-COMP-771',
    vendorName: 'أطلس كوبكو للحلول الصناعية',
    hasReceipt: false,
    status: 'rejected',
    submittedBy: 'خالد الظاهري',
    submittedAt: '2026-09-18 10:15',
    approvedBy: 'فاطمة الكعبي',
    approvedAt: '2026-09-18 12:30',
    rejectionReason: 'عدم إرفاق الفاتورة الضريبية الأصلية وإذن التسليم المعتمد من مهندس الموقع.',
  },
  {
    id: 'exp-19',
    code: 'EXP-919',
    fundId: 'fund-5',
    fundName: 'عهدة مشاريع محطة الطاقة الشمسية - العين',
    amount: 2700,
    taxAmount: 135,
    totalWithTax: 2835,
    category: 'materials',
    description: 'كوابل اتصال فايبر أوبتك وتجهيزات ربط غرف التحكم بمحطة الأرصاد',
    invoiceNumber: 'OPTIC-LINK-330',
    vendorName: 'شبكات الألياف الضوئية الحديثة',
    hasReceipt: true,
    status: 'settled',
    submittedBy: 'طارق السويدي',
    submittedAt: '2026-08-28 09:00',
    approvedBy: 'فاطمة الكعبي',
    approvedAt: '2026-08-28 12:00',
  },
  {
    id: 'exp-20',
    code: 'EXP-920',
    fundId: 'fund-3',
    fundName: 'عهدة نثريات وضيافة العمليات',
    amount: 880,
    taxAmount: 44,
    totalWithTax: 924,
    category: 'materials',
    description: 'قرطاسية وأوراق طباعة مخططات A3 وأحبار للطابعة الميدانية في كرفان الإدارة',
    invoiceNumber: 'OFFICE-ONE-442',
    vendorName: 'مكتبة دبي للتوزيع',
    hasReceipt: true,
    status: 'approved',
    submittedBy: 'م. راشد المزروعي',
    submittedAt: '2026-09-10 11:30',
    approvedBy: 'سارة الهاشمي',
    approvedAt: '2026-09-10 14:00',
  }
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'tsk-1',
    title: 'تحديث المحطة الكهربائية الفرعية في القطاع C',
    description: 'فصل القواطع القديمة، تركيب لوحة التوزيع الجديدة، وإجراء اختبارات السلامة والتأريض بمشاركة استشاري المشروع.',
    priority: 'urgent',
    status: 'in_progress',
    assigneeId: 'usr-4',
    assigneeName: 'أحمد الحمادي',
    assigneeAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    dueDate: '2026-09-24',
    startDate: '2026-09-12',
    location: 'المنطقة الصناعية - موقع 4B',
    category: 'كهرباء وطاقة',
    budget: 8500,
    spentAmount: 6300,
    tags: ['كهرباء', 'سلامة', 'موقع-4B'],
    fundId: 'fund-1',
    checklist: [
      { id: 'chk-1', text: 'عزل التيار وإصدار تصريح العمل الساخن', completed: true },
      { id: 'chk-2', text: 'تفكيك القواطع التالفة القديمة', completed: true },
      { id: 'chk-3', text: 'تثبيت اللوحة الجديدة وتوصيل الكابلات 16 ملم', completed: true },
      { id: 'chk-4', text: 'فحص المقاومة والتأريض مع الاستشاري', completed: false },
      { id: 'chk-5', text: 'إعادة التشغيل التجريبي وإصدار شهادة الإنجاز', completed: false },
    ],
    history: [
      { id: 'h-1', action: 'إنشاء المهمة وتكليف أحمد الحمادي', performedBy: 'م. راشد المزروعي', timestamp: '2026-09-12 09:00' },
      { id: 'h-2', action: 'بدء العمل الميداني وعزل التيار', performedBy: 'أحمد الحمادي', timestamp: '2026-09-12 10:15' },
      { id: 'h-3', action: 'صرف 3,360 درهم لمواد الكابلات', performedBy: 'أحمد الحمادي', timestamp: '2026-09-12 11:30' },
      { id: 'h-4', action: 'إنجاز 60% من الأعمال الميكانيكية والكهربائية', performedBy: 'أحمد الحمادي', timestamp: '2026-09-18 17:00' },
    ],
    createdAt: '2026-09-12',
  },
  {
    id: 'tsk-2',
    title: 'فحص وتشغيل مضخات التبريد المركزية',
    description: 'الفحص الدوري لمنظومة ضخ مياه التبريد، تنظيف الفلاتر، وتغيير مانعات التسرب قبل بدء ذروة العمليات التشغيلية.',
    priority: 'high',
    status: 'review',
    assigneeId: 'usr-5',
    assigneeName: 'خالد الظاهري',
    assigneeAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    dueDate: '2026-09-22',
    startDate: '2026-09-14',
    location: 'مجمع المستودعات المركزية - القوز',
    category: 'ميكانيكا وتبريد',
    budget: 4000,
    spentAmount: 2372.5,
    tags: ['تبريد', 'فحص دوري', 'مستودعات'],
    fundId: 'fund-2',
    checklist: [
      { id: 'chk-21', text: 'قياس درجات الحرارة قبل التوقف', completed: true },
      { id: 'chk-22', text: 'تفريغ وتنظيف مصافي الشفط', completed: true },
      { id: 'chk-23', text: 'استبدال حلقات العزل الهيدروليكي', completed: true },
      { id: 'chk-24', text: 'تسجيل قراءات الضغط بعد التشغيل', completed: true },
    ],
    history: [
      { id: 'h-21', action: 'بدء المهمة وتسجيل القراءات الأولية', performedBy: 'خالد الظاهري', timestamp: '2026-09-14 09:30' },
      { id: 'h-22', action: 'إنهاء أعمال الصيانة ورفع التقرير للمراجعة', performedBy: 'خالد الظاهري', timestamp: '2026-09-19 14:40' },
    ],
    createdAt: '2026-09-14',
  },
  {
    id: 'tsk-3',
    title: 'معايرة أنظمة قياس الضغط الهوائي',
    description: 'إعادة ضبط أجهزة القياس الرقمية ومطابقتها مع المعايير القياسية للهيئة لضمان دقة العمليات الصناعية.',
    priority: 'medium',
    status: 'in_progress',
    assigneeId: 'usr-5',
    assigneeName: 'خالد الظاهري',
    assigneeAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    dueDate: '2026-09-26',
    startDate: '2026-09-18',
    location: 'ورشة الفحص الفني - جبل علي',
    category: 'معايرة وجودة',
    budget: 2000,
    spentAmount: 892.5,
    tags: ['معايرة', 'جودة', 'جبل علي'],
    fundId: 'fund-2',
    checklist: [
      { id: 'chk-31', text: 'فحص الحساسات وشهادات المعايرة السابقة', completed: true },
      { id: 'chk-32', text: 'توصيل جهاز المعايرة المرجعي المعتمد', completed: true },
      { id: 'chk-33', text: 'استخراج شهادة المعايرة وتحديث ملصق الفحص', completed: false },
    ],
    history: [
      { id: 'h-31', action: 'استلام الأجهزة وبدء المعايرة', performedBy: 'خالد الظاهري', timestamp: '2026-09-18 10:00' },
    ],
    createdAt: '2026-09-18',
  },
  {
    id: 'tsk-4',
    title: 'تجهيز موقع الإنشاءات للزيارة الرقابية السنوية',
    description: 'ترتيب معدات السلامة، فحص طفايات الحريق، تنظيف المسارات، وتجهيز ملف السجلات الفنية للبلدية والدفاع المدني.',
    priority: 'urgent',
    status: 'todo',
    assigneeId: 'usr-4',
    assigneeName: 'أحمد الحمادي',
    assigneeAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    dueDate: '2026-09-23',
    startDate: '2026-09-20',
    location: 'موقع الإنشاءات الجديد - الشارقة',
    category: 'سلامة ورقابة',
    budget: 3500,
    spentAmount: 0,
    tags: ['تفتيش', 'بلدية', 'سلامة'],
    fundId: 'fund-1',
    checklist: [
      { id: 'chk-41', text: 'فحص تواريخ صلاحية طفايات الحريق وخراطيم الطوارئ', completed: false },
      { id: 'chk-42', text: 'التأكد من ارتداء جميع العمال للخوذ والسترات العاكسة', completed: false },
      { id: 'chk-43', text: 'تجهيز سجلات الصيانة وفواتير العهد للمراجعة', completed: false },
    ],
    history: [
      { id: 'h-41', action: 'إنشاء المهمة وتحديد موعد التفتيش مع البلدية', performedBy: 'م. راشد المزروعي', timestamp: '2026-09-19 11:00' },
    ],
    createdAt: '2026-09-19',
  },
  {
    id: 'tsk-5',
    title: 'استبدال كواشف الدخان في المستودع اللوجستي',
    description: 'استبدال 18 كاشف دخان قديم بكواشف ضوئية ذكية مرتبطة بلوحة التحكم الرئيسية لإدارة الدفاع المدني.',
    priority: 'low',
    status: 'completed',
    assigneeId: 'usr-5',
    assigneeName: 'خالد الظاهري',
    assigneeAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    dueDate: '2026-09-15',
    startDate: '2026-09-08',
    location: 'المستودع الرئيسي رقم 2',
    category: 'دفاع مدني وحريق',
    budget: 5000,
    spentAmount: 4800,
    tags: ['دفاع مدني', 'مستودعات', 'مكتمل'],
    fundId: 'fund-2',
    checklist: [
      { id: 'chk-51', text: 'توريد كواشف الدخان المعتمدة', completed: true },
      { id: 'chk-52', text: 'تركيب الكواشف وبرمجتها على الشبكة', completed: true },
      { id: 'chk-53', text: 'إجراء اختبار الدخان الوهمي بنجاح', completed: true },
    ],
    history: [
      { id: 'h-51', action: 'اكتمال المهمة واعتماد تقرير الفحص', performedBy: 'خالد الظاهري', timestamp: '2026-09-15 16:00' },
    ],
    createdAt: '2026-09-08',
  },
  {
    id: 'tsk-6',
    title: 'غسيل وتطهير مصفوفات الألواح الشمسية - القطاع الجنوبي',
    description: 'تنفيذ دورة التنظيف المجدولة لإزالة تراكم الغبار والرمال لرفع كفاءة إنتاج الطاقة بنسبة لا تقل عن 14%.',
    priority: 'high',
    status: 'in_progress',
    assigneeId: 'usr-6',
    assigneeName: 'طارق السويدي',
    assigneeAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    dueDate: '2026-09-25',
    startDate: '2026-09-17',
    location: 'محطة الطاقة الشمسية - طريق العين',
    category: 'طاقة نظيفة',
    budget: 6500,
    spentAmount: 6195,
    tags: ['طاقة شمسية', 'تنظيف', 'العين'],
    fundId: 'fund-5',
    checklist: [
      { id: 'chk-61', text: 'فحص جاهزية صهاريج المياه المعالجة', completed: true },
      { id: 'chk-62', text: 'تنظيف 12 صفاً في القطاع الجنوبي A', completed: true },
      { id: 'chk-63', text: 'تنظيف القطاع B وقياس معامل الانعكاس', completed: false },
      { id: 'chk-64', text: 'رفع تقرير تحسن إنتاجية الكيلوواط', completed: false },
    ],
    history: [
      { id: 'h-61', action: 'انطلاق فرق الغسيل الميداني في ساعات الصباح الباكر', performedBy: 'طارق السويدي', timestamp: '2026-09-17 06:00' },
      { id: 'h-62', action: 'صرف فواتير وقود الصهاريج ومواد التنظيف', performedBy: 'طارق السويدي', timestamp: '2026-09-18 13:20' },
    ],
    createdAt: '2026-09-17',
  },
  {
    id: 'tsk-7',
    title: 'الفحص الفني الدوري وتجديد ترخيص أسطول العمليات',
    description: 'إدخال 6 مركبات خدمة وشاحنتين لورشة الفحص الفني المعتمدة لاستخراج شهادات السلامة المرورية وتجديد التأمين.',
    priority: 'medium',
    status: 'in_progress',
    assigneeId: 'usr-5',
    assigneeName: 'خالد الظاهري',
    assigneeAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    dueDate: '2026-09-28',
    startDate: '2026-09-15',
    location: 'مركز الفحص الفني لمركبات دبي - القصيص',
    category: 'خدمات لوجستية',
    budget: 3000,
    spentAmount: 1260,
    tags: ['مركبات', 'ترخيص', 'لوجستيات'],
    fundId: 'fund-6',
    checklist: [
      { id: 'chk-71', text: 'صيانة الفرامل واستبدال الإطارات المستهلكة', completed: true },
      { id: 'chk-72', text: 'اجتياز الفحص الفني للمركبات 1 و 2 و 3', completed: true },
      { id: 'chk-73', text: 'إدخال الشاحنة الثقيلة رقم 4 للفحص النهائي', completed: false },
    ],
    history: [
      { id: 'h-71', action: 'بدء عمليات الصيانة التجهيزية للأسطول', performedBy: 'خالد الظاهري', timestamp: '2026-09-15 08:30' },
    ],
    createdAt: '2026-09-15',
  },
  {
    id: 'tsk-8',
    title: 'تنظيم ورشة تدريب السلامة لفرق الموقع الجديد',
    description: 'تدريب 25 فنياً وعاملاً على إجراءات الإخلاء الطارئ، استخدام طفايات الحريق، وبروتوكول الإبلاغ عن الحوادث.',
    priority: 'medium',
    status: 'completed',
    assigneeId: 'usr-2',
    assigneeName: 'م. راشد المزروعي',
    assigneeAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    dueDate: '2026-09-17',
    startDate: '2026-09-16',
    location: 'قاعة التدريب بالموقع الإنشائي - الشارقة',
    category: 'تدريب وجودة',
    budget: 1500,
    spentAmount: 472.5,
    tags: ['سلامة', 'تدريب', 'مكتمل'],
    fundId: 'fund-3',
    checklist: [
      { id: 'chk-81', text: 'تجهيز المادة التدريبية وعروض الفيديو التوضيحية', completed: true },
      { id: 'chk-82', text: 'إجراء المحاكاة العملية للإخلاء ومكافحة الحريق', completed: true },
      { id: 'chk-83', text: 'توزيع شهادات الحضور وتوثيق السجل في ملف التدريب', completed: true },
    ],
    history: [
      { id: 'h-81', action: 'اكتمال الورشة التدريبية بنجاح وتسجيل الحضور بنسبة 100%', performedBy: 'م. راشد المزروعي', timestamp: '2026-09-17 15:00' },
    ],
    createdAt: '2026-09-16',
  },
  {
    id: 'tsk-9',
    title: 'استبدال محول العزل ومراجعة منظومة التأريض لمحطة الطاقة',
    description: 'توريد وتركيب محول عزل عالي الكفاءة في المحطة الفرعية B2 لحماية العواكس من التذبذبات الكهربائية.',
    priority: 'urgent',
    status: 'review',
    assigneeId: 'usr-6',
    assigneeName: 'طارق السويدي',
    assigneeAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    dueDate: '2026-09-21',
    startDate: '2026-09-18',
    location: 'محطة الطاقة الشمسية - القطاع الشمالي',
    category: 'كهرباء ومحولات',
    budget: 7000,
    spentAmount: 4830,
    tags: ['محولات', 'تأريض', 'طاقة'],
    fundId: 'fund-5',
    checklist: [
      { id: 'chk-91', text: 'تفريغ وتبريد غرفة المحول المعطوب', completed: true },
      { id: 'chk-92', text: 'تثبيت المحول الجديد وربط القضبان النحاسية', completed: true },
      { id: 'chk-93', text: 'قياس مقاومة التأريض (أقل من 2 أوم)', completed: true },
      { id: 'chk-94', text: 'اعتماد محضر الاستلام الميداني مع الاستشاري', completed: false },
    ],
    history: [
      { id: 'h-91', action: 'إنهاء أعمال التركيب ورفع ملف الفحص للتدقيق الفني', performedBy: 'طارق السويدي', timestamp: '2026-09-19 16:30' },
    ],
    createdAt: '2026-09-18',
  },
  {
    id: 'tsk-10',
    title: 'تأهيل وتحديث غرفة المراقبة والتحكم SCADA',
    description: 'صيانة شاشات المراقبة الجدارية، استبدال وحدات التغذية غير المنقطعة (UPS)، وتحديث برامج تسجيل البيانات اللحظية.',
    priority: 'low',
    status: 'todo',
    assigneeId: 'usr-2',
    assigneeName: 'م. راشد المزروعي',
    assigneeAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    dueDate: '2026-09-30',
    startDate: '2026-09-25',
    location: 'المقر الرئيسي للعمليات - الطابق 2',
    category: 'تحكم وأنظمة',
    budget: 4500,
    spentAmount: 0,
    tags: ['سكادا', 'تحكم', 'غرفة-العمليات'],
    fundId: 'fund-3',
    checklist: [
      { id: 'chk-101', text: 'فحص بطاريات الـ UPS واختبار زمن التفريغ', completed: false },
      { id: 'chk-102', text: 'تحديث تراخيص برمجيات السكادا الصناعية', completed: false },
      { id: 'chk-103', text: 'إعادة ضبط قنوات الإشارات مع المحطات الميدانية', completed: false },
    ],
    history: [
      { id: 'h-101', action: 'جدولة المهمة لنهاية الشهر بالتنسيق مع قسم تكنولوجيا المعلومات', performedBy: 'م. راشد المزروعي', timestamp: '2026-09-19 10:00' },
    ],
    createdAt: '2026-09-19',
  }
];

export const INITIAL_SETTLEMENTS: Settlement[] = [
  {
    id: 'stl-1',
    code: 'STL-2026-08',
    fundId: 'fund-1',
    fundName: 'عهدة مشاريع المنطقة الصناعية A',
    holderName: 'أحمد الحمادي',
    periodStart: '2026-08-01',
    periodEnd: '2026-08-31',
    advanceAmount: 25000,
    totalExpenses: 21650,
    remainingAmount: 3350,
    status: 'approved',
    expenseIds: ['exp-prev-1', 'exp-prev-2', 'exp-prev-3'],
    expensesCount: 14,
    submittedAt: '2026-09-02 11:30',
    settledBy: 'أحمد الحمادي',
    approvedBy: 'فاطمة الكعبي',
    approvedAt: '2026-09-04 15:00',
    auditNotes: 'تمت مطابقة جميع الفواتير الضريبية وتوريد المتبقي لإعادة التغذية بمبلغ 21,650 درهم.',
    settlementVoucherNumber: 'VCH-STL-2026-0089',
  },
  {
    id: 'stl-2',
    code: 'STL-2026-09',
    fundId: 'fund-2',
    fundName: 'عهدة الصيانة والتشغيل الميداني',
    holderName: 'خالد الظاهري',
    periodStart: '2026-09-01',
    periodEnd: '2026-09-15',
    advanceAmount: 15000,
    totalExpenses: 472.5,
    remainingAmount: 14527.5,
    status: 'under_review',
    expenseIds: ['exp-7'],
    expensesCount: 3,
    submittedAt: '2026-09-17 10:15',
    settledBy: 'خالد الظاهري',
    auditNotes: 'قيد مراجعة فواتير الشحن وأذونات التسليم المرفقة ومطابقتها مع كشف الحساب المصرفي.',
  },
  {
    id: 'stl-3',
    code: 'STL-2026-07',
    fundId: 'fund-1',
    fundName: 'عهدة مشاريع المنطقة الصناعية A',
    holderName: 'أحمد الحمادي',
    periodStart: '2026-07-01',
    periodEnd: '2026-07-31',
    advanceAmount: 25000,
    totalExpenses: 23100,
    remainingAmount: 1900,
    status: 'approved',
    expenseIds: ['exp-july-1', 'exp-july-2'],
    expensesCount: 16,
    submittedAt: '2026-08-03 09:45',
    settledBy: 'أحمد الحمادي',
    approvedBy: 'فاطمة الكعبي',
    approvedAt: '2026-08-05 14:20',
    auditNotes: 'تسوية دورية شهر يوليو مكتملة ومطابقة للسجلات الضريبية.',
    settlementVoucherNumber: 'VCH-STL-2026-0072',
  },
  {
    id: 'stl-4',
    code: 'STL-2026-SOLAR-08',
    fundId: 'fund-5',
    fundName: 'عهدة مشاريع محطة الطاقة الشمسية - العين',
    holderName: 'طارق السويدي',
    periodStart: '2026-08-01',
    periodEnd: '2026-08-31',
    advanceAmount: 20000,
    totalExpenses: 18450,
    remainingAmount: 1550,
    status: 'approved',
    expenseIds: ['exp-19'],
    expensesCount: 9,
    submittedAt: '2026-09-01 10:00',
    settledBy: 'طارق السويدي',
    approvedBy: 'سارة الهاشمي',
    approvedAt: '2026-09-03 13:10',
    auditNotes: 'تمت مراجعة عقود صيانة غرف التحكم وتغذية العهدة بدفعة شهر سبتمبر.',
    settlementVoucherNumber: 'VCH-STL-2026-0085',
  },
  {
    id: 'stl-5',
    code: 'STL-2026-HOSP-08',
    fundId: 'fund-3',
    fundName: 'عهدة نثريات وضيافة العمليات',
    holderName: 'م. راشد المزروعي',
    periodStart: '2026-08-10',
    periodEnd: '2026-08-31',
    advanceAmount: 10000,
    totalExpenses: 7420,
    remainingAmount: 2580,
    status: 'approved',
    expenseIds: ['exp-hosp-1', 'exp-hosp-2'],
    expensesCount: 8,
    submittedAt: '2026-09-02 14:00',
    settledBy: 'م. راشد المزروعي',
    approvedBy: 'فاطمة الكعبي',
    approvedAt: '2026-09-04 11:30',
    auditNotes: 'معتمدة ومطابقة لمصروفات استضافة وتنسيق البلديات والجهات الحكومية.',
    settlementVoucherNumber: 'VCH-STL-2026-0088',
  }
];

export const INITIAL_FOLLOW_UPS: FollowUp[] = [
  {
    id: 'flw-1',
    taskId: 'tsk-1',
    taskTitle: 'تحديث المحطة الكهربائية الفرعية في القطاع C',
    title: 'تأكيد موعد استشاري السلامة لفحص التأريض غداً',
    urgency: 'critical',
    assignedTo: 'أحمد الحمادي',
    scheduledDate: '2026-09-21',
    status: 'pending',
    notes: 'يجب التنسيق مع الاستشاري قبل الساعة 11:00 صباحاً لتجنب تأخير جدول الإغلاق.',
  },
  {
    id: 'flw-2',
    taskId: 'tsk-4',
    taskTitle: 'تجهيز موقع الإنشاءات للزيارة الرقابية السنوية',
    title: 'مراجعة ملف الدفاع المدني وتراخيص المعدات قبل زيارة البلدية',
    urgency: 'high',
    assignedTo: 'م. راشد المزروعي',
    scheduledDate: '2026-09-22',
    status: 'pending',
    notes: 'التأكد من ختم مهندس الموقع وتواجد السجلات الأصلية في كابينة العمليات.',
  },
  {
    id: 'flw-3',
    title: 'متابعة إعادة تغذية عهدة المنطقة الصناعية A مع الحسابات',
    urgency: 'high',
    assignedTo: 'فاطمة الكعبي',
    scheduledDate: '2026-09-21',
    status: 'pending',
    notes: 'الرصيد المتبقي أقل من 35% وهناك أعمال صيانة قادمة في نهاية الأسبوع.',
  },
  {
    id: 'flw-4',
    taskId: 'tsk-2',
    taskTitle: 'فحص وتشغيل مضخات التبريد المركزية',
    title: 'أخذ عينة زيت بعد 48 ساعة من التشغيل للتأكد من انعدام الشوائب',
    urgency: 'normal',
    assignedTo: 'خالد الظاهري',
    scheduledDate: '2026-09-24',
    status: 'resolved',
    notes: 'تم فحص العينة بمختبر الموقع والقراءات ممتازة ومطابقة للمواصفة القياسية.',
  },
  {
    id: 'flw-5',
    taskId: 'tsk-6',
    taskTitle: 'غسيل وتطهير مصفوفات الألواح الشمسية - القطاع الجنوبي',
    title: 'معاينة قراءات الانعكاس ورفع تقرير الإنتاجية قبل إغلاق المهمة',
    urgency: 'high',
    assignedTo: 'طارق السويدي',
    scheduledDate: '2026-09-25',
    status: 'pending',
    notes: 'مقارنة إنتاج المحطة الفعلي مع البيانات التاريخية للشهر الماضي لنفس القطاع.',
  },
  {
    id: 'flw-6',
    title: 'تقديم تسوية عهدة محطة الطاقة الشمسية لشهر سبتمبر',
    urgency: 'critical',
    assignedTo: 'طارق السويدي',
    scheduledDate: '2026-09-26',
    status: 'pending',
    notes: 'الرصيد وصل إلى 21% ويتوجب رفع التسوية قبل يوم الأحد لتفادي انقطاع السيولة التشغيلية.',
  },
  {
    id: 'flw-7',
    taskId: 'tsk-7',
    taskTitle: 'الفحص الفني الدوري وتجديد ترخيص أسطول العمليات',
    title: 'استلام بطاقات ملكية الشاحنات المجددة من هيئة الطرق والمواصلات',
    urgency: 'normal',
    assignedTo: 'خالد الظاهري',
    scheduledDate: '2026-09-28',
    status: 'pending',
    notes: 'تحديث بطاقات سالك وتوزيع بوالص التأمين على سائقي المركبات الميدانية.',
  }
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-1',
    userId: 'usr-3',
    userName: 'فاطمة الكعبي',
    userRole: 'finance_officer',
    action: 'اعتماد تسوية مالية عهدة رقم PCF-2026-001',
    actionType: 'settle',
    entity: 'settlement',
    entityId: 'stl-1',
    details: 'تم اعتماد تسوية شهر أغسطس بمبلغ 21,650 درهم بعد استيفاء 14 فاتورة ضريبية.',
    timestamp: '2026-09-19 15:45:12',
    ipAddress: '192.168.10.42',
  },
  {
    id: 'aud-2',
    userId: 'usr-3',
    userName: 'فاطمة الكعبي',
    userRole: 'finance_officer',
    action: 'رفض طلب صرف مصروف عهدة EXP-906',
    actionType: 'reject',
    entity: 'expense',
    entityId: 'exp-6',
    details: 'الرفض لتجاوز الحد الأقصى لصرف العهدة الفردي (7,875 درهم > 5,000 درهم).',
    timestamp: '2026-09-17 14:00:20',
    ipAddress: '192.168.10.42',
  },
  {
    id: 'aud-3',
    userId: 'usr-4',
    userName: 'أحمد الحمادي',
    userRole: 'field_officer',
    action: 'تحديث قائمة فحص المهمة tsk-1',
    actionType: 'update',
    entity: 'task',
    entityId: 'tsk-1',
    details: 'إتمام البند (تثبيت اللوحة الجديدة وتوصيل الكابلات 16 ملم).',
    timestamp: '2026-09-18 17:00:00',
    ipAddress: '10.0.4.18',
  },
  {
    id: 'aud-4',
    userId: 'usr-2',
    userName: 'م. راشد المزروعي',
    userRole: 'ops_manager',
    action: 'إنشاء مهمة تشغيلية جديدة tsk-4',
    actionType: 'create',
    entity: 'task',
    entityId: 'tsk-4',
    details: 'إنشاء مهمة تجهيز موقع الإنشاءات للزيارة الرقابية بميزانية 3,500 درهم.',
    timestamp: '2026-09-19 11:00:00',
    ipAddress: '192.168.10.15',
  },
  {
    id: 'aud-5',
    userId: 'usr-1',
    userName: 'سلطان المنصوري',
    userRole: 'admin',
    action: 'تعديل سقف العهدة النقدية لطوارئ السلامة',
    actionType: 'update',
    entity: 'fund',
    entityId: 'fund-4',
    details: 'رفع التخصيص من 20,000 إلى 30,000 درهم بقرار إداري.',
    timestamp: '2026-09-10 09:30:00',
    ipAddress: '192.168.10.2',
  },
  {
    id: 'aud-6',
    userId: 'usr-7',
    userName: 'سارة الهاشمي',
    userRole: 'finance_officer',
    action: 'اعتماد تسوية عهدة محطة الطاقة الشمسية STL-2026-SOLAR-08',
    actionType: 'settle',
    entity: 'settlement',
    entityId: 'stl-4',
    details: 'مطابقة 9 فواتير ضريبية بإجمالي 18,450 درهم وإصدار سند الإغلاق المالي.',
    timestamp: '2026-09-03 13:10:00',
    ipAddress: '192.168.10.45',
  },
  {
    id: 'aud-7',
    userId: 'usr-6',
    userName: 'طارق السويدي',
    userRole: 'field_officer',
    action: 'تسجيل فاتورة صيانة المحول الفرعي EXP-915',
    actionType: 'create',
    entity: 'expense',
    entityId: 'exp-15',
    details: 'قيد مصروف بمبلغ 4,830 درهم لشركة ABB لصيانة محول العزل في العين.',
    timestamp: '2026-09-19 14:00:00',
    ipAddress: '10.0.8.22',
  },
  {
    id: 'aud-8',
    userId: 'usr-3',
    userName: 'فاطمة الكعبي',
    userRole: 'finance_officer',
    action: 'رفض مصروف ورشة أطلس كوبكو EXP-918',
    actionType: 'reject',
    entity: 'expense',
    entityId: 'exp-18',
    details: 'رفض لعدم إرفاق الفاتورة الضريبية الأصلية وإذن استلام الموقع.',
    timestamp: '2026-09-18 12:30:00',
    ipAddress: '192.168.10.42',
  }
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'تنبيه انخفاض رصيد العهدة',
    message: 'عهدة مشاريع محطة الطاقة الشمسية - العين وصلت إلى 21% من رصيدها، يتوجب تقديم طلب التسوية.',
    type: 'warning',
    isRead: false,
    createdAt: 'منذ ساعة',
    targetView: 'funds',
  },
  {
    id: 'notif-2',
    title: 'تنبيه استنزاف عهدة وشيك',
    message: 'عهدة مشاريع المنطقة الصناعية A قاربت سقف التنبيه (33.8% متبقي).',
    type: 'warning',
    isRead: false,
    createdAt: 'منذ ساعتين',
    targetView: 'funds',
  },
  {
    id: 'notif-3',
    title: 'مصروف صيانة محول بانتظار الاعتماد',
    message: 'قام طارق السويدي برفع فاتورة صيانة محطة الطاقة بمبلغ 4,830 درهم.',
    type: 'info',
    isRead: false,
    createdAt: 'منذ 3 ساعات',
    targetView: 'expenses',
  },
  {
    id: 'notif-4',
    title: 'زيارة التفتيش والبلدية غداً',
    message: 'مهمة تجهيز موقع الإنشاءات للزيارة الرقابية السنوية تنتهي خلال 48 ساعة.',
    type: 'alert',
    isRead: false,
    createdAt: 'منذ 5 ساعات',
    targetView: 'tasks',
  },
  {
    id: 'notif-5',
    title: 'تم اعتماد تسوية شهر أغسطس',
    message: 'تم تدقيق وإغلاق التسوية STL-2026-08 بنجاح برصيد 21,650 درهم وإصدار سند الإغلاق.',
    type: 'success',
    isRead: true,
    createdAt: 'منذ يومين',
    targetView: 'settlements',
  },
  {
    id: 'notif-6',
    title: 'رفض طلب شراء مولد كهربائي',
    message: 'تم رفض طلب الصرف EXP-906 لتجاوز سقف الصرف الفردي بدون أمر شراء رسمي.',
    type: 'alert',
    isRead: true,
    createdAt: 'منذ 3 أيام',
    targetView: 'expenses',
  }
];
