import { Role, PermissionRule } from '../../types/domain';

export const ROLE_PERMISSIONS: Record<Role, Record<string, { view: boolean; create: boolean; edit: boolean; delete: boolean; approve: boolean }>> = {
  admin: {
    dashboard: { view: true, create: true, edit: true, delete: true, approve: true },
    tasks: { view: true, create: true, edit: true, delete: true, approve: true },
    followUps: { view: true, create: true, edit: true, delete: true, approve: true },
    funds: { view: true, create: true, edit: true, delete: true, approve: true },
    expenses: { view: true, create: true, edit: true, delete: true, approve: true },
    settlements: { view: true, create: true, edit: true, delete: true, approve: true },
    calendar: { view: true, create: true, edit: true, delete: true, approve: true },
    reports: { view: true, create: true, edit: true, delete: true, approve: true },
    team: { view: true, create: true, edit: true, delete: true, approve: true },
    users: { view: true, create: true, edit: true, delete: true, approve: true },
    roles: { view: true, create: true, edit: true, delete: true, approve: true },
    audit: { view: true, create: false, edit: false, delete: false, approve: false },
    settings: { view: true, create: true, edit: true, delete: true, approve: true },
    aiAdvisor: { view: true, create: true, edit: true, delete: false, approve: true },
  },
  ops_manager: {
    dashboard: { view: true, create: false, edit: false, delete: false, approve: false },
    tasks: { view: true, create: true, edit: true, delete: true, approve: true },
    followUps: { view: true, create: true, edit: true, delete: true, approve: true },
    funds: { view: true, create: false, edit: false, delete: false, approve: false },
    expenses: { view: true, create: true, edit: true, delete: false, approve: false },
    settlements: { view: true, create: false, edit: false, delete: false, approve: false },
    calendar: { view: true, create: true, edit: true, delete: true, approve: false },
    reports: { view: true, create: true, edit: false, delete: false, approve: false },
    team: { view: true, create: true, edit: true, delete: false, approve: false },
    users: { view: true, create: false, edit: false, delete: false, approve: false },
    roles: { view: true, create: false, edit: false, delete: false, approve: false },
    audit: { view: true, create: false, edit: false, delete: false, approve: false },
    settings: { view: false, create: false, edit: false, delete: false, approve: false },
    aiAdvisor: { view: true, create: true, edit: false, delete: false, approve: false },
  },
  finance_officer: {
    dashboard: { view: true, create: false, edit: false, delete: false, approve: false },
    tasks: { view: true, create: false, edit: false, delete: false, approve: false },
    followUps: { view: true, create: false, edit: false, delete: false, approve: false },
    funds: { view: true, create: true, edit: true, delete: false, approve: true },
    expenses: { view: true, create: true, edit: true, delete: true, approve: true },
    settlements: { view: true, create: true, edit: true, delete: false, approve: true },
    calendar: { view: true, create: false, edit: false, delete: false, approve: false },
    reports: { view: true, create: true, edit: true, delete: false, approve: true },
    team: { view: true, create: false, edit: false, delete: false, approve: false },
    users: { view: false, create: false, edit: false, delete: false, approve: false },
    roles: { view: false, create: false, edit: false, delete: false, approve: false },
    audit: { view: true, create: false, edit: false, delete: false, approve: false },
    settings: { view: true, create: false, edit: true, delete: false, approve: false },
    aiAdvisor: { view: true, create: true, edit: false, delete: false, approve: false },
  },
  field_officer: {
    dashboard: { view: true, create: false, edit: false, delete: false, approve: false },
    tasks: { view: true, create: false, edit: true, delete: false, approve: false },
    followUps: { view: true, create: true, edit: true, delete: false, approve: false },
    funds: { view: true, create: false, edit: false, delete: false, approve: false },
    expenses: { view: true, create: true, edit: false, delete: false, approve: false },
    settlements: { view: true, create: false, edit: false, delete: false, approve: false },
    calendar: { view: true, create: false, edit: false, delete: false, approve: false },
    reports: { view: false, create: false, edit: false, delete: false, approve: false },
    team: { view: true, create: false, edit: false, delete: false, approve: false },
    users: { view: false, create: false, edit: false, delete: false, approve: false },
    roles: { view: false, create: false, edit: false, delete: false, approve: false },
    audit: { view: false, create: false, edit: false, delete: false, approve: false },
    settings: { view: false, create: false, edit: false, delete: false, approve: false },
    aiAdvisor: { view: false, create: false, edit: false, delete: false, approve: false },
  },
  viewer: {
    dashboard: { view: true, create: false, edit: false, delete: false, approve: false },
    tasks: { view: true, create: false, edit: false, delete: false, approve: false },
    followUps: { view: true, create: false, edit: false, delete: false, approve: false },
    funds: { view: true, create: false, edit: false, delete: false, approve: false },
    expenses: { view: true, create: false, edit: false, delete: false, approve: false },
    settlements: { view: true, create: false, edit: false, delete: false, approve: false },
    calendar: { view: true, create: false, edit: false, delete: false, approve: false },
    reports: { view: true, create: false, edit: false, delete: false, approve: false },
    team: { view: true, create: false, edit: false, delete: false, approve: false },
    users: { view: false, create: false, edit: false, delete: false, approve: false },
    roles: { view: false, create: false, edit: false, delete: false, approve: false },
    audit: { view: false, create: false, edit: false, delete: false, approve: false },
    settings: { view: false, create: false, edit: false, delete: false, approve: false },
    aiAdvisor: { view: false, create: false, edit: false, delete: false, approve: false },
  },
};

export const ROLE_LABELS: Record<Role, { ar: string; en: string; label: string; titleAr: string; badgeColor: string; description: string }> = {
  admin: {
    ar: 'مدير النظام التنفيذي',
    label: 'مدير النظام',
    titleAr: 'مدير النظام التنفيذي',
    en: 'System Administrator',
    badgeColor: 'bg-purple-100 text-purple-800 border-purple-200',
    description: 'صلاحيات مطلقة لإدارة المنصة، المستخدمين، السياسات المالية وإعدادات النظام.',
  },
  ops_manager: {
    ar: 'مدير العمليات الميدانية',
    label: 'مدير العمليات',
    titleAr: 'مدير العمليات الميدانية',
    en: 'Operations Manager',
    badgeColor: 'bg-blue-100 text-blue-800 border-blue-200',
    description: 'إدارة وتوجيه فرق العمل، توزيع المهام، المتابعات الميدانية، والتقارير التشغيلية.',
  },
  finance_officer: {
    ar: 'المسؤول المالي والتدقيق',
    label: 'المسؤول المالي',
    titleAr: 'المسؤول المالي والتدقيق',
    en: 'Finance & Audit Officer',
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-200',
    description: 'إدارة وتغذية صناديق العهد، اعتماد فواتير المصروفات، إجراء التسويات والمطابقات.',
  },
  field_officer: {
    ar: 'مشرف / منفذ ميداني',
    label: 'مشرف ميداني',
    titleAr: 'مشرف / منفذ ميداني',
    en: 'Field Operations Officer',
    badgeColor: 'bg-amber-100 text-amber-800 border-amber-200',
    description: 'تنفيذ المهام، تحديث قوائم الفحص، رفع فواتير المصروفات من العهدة المسندة إليه.',
  },
  viewer: {
    ar: 'مطلع ومراقب',
    label: 'مراقب عام',
    titleAr: 'مطلع ومراقب',
    en: 'Observer / Auditor',
    badgeColor: 'bg-slate-100 text-slate-800 border-slate-200',
    description: 'صلاحيات استعراض ومراقبة التقارير ومؤشرات الأداء دون حق التعديل أو الاعتماد.',
  },
};

export function hasPermission(role: Role, module: string, action: 'view' | 'create' | 'edit' | 'delete' | 'approve'): boolean {
  const roleRules = ROLE_PERMISSIONS[role];
  if (!roleRules || !roleRules[module]) return false;
  return roleRules[module][action] ?? false;
}
